### ISSUE TITLE
Feedback for errors in Revision scripts

### ISSUE THREAD

**Issue by x56mike** [victorstanciu/dbv#86]
Thanks for a very handy tool. I'm using it with MariaDB with the MySQL connector.

I'm finding it frustrating that there is no feedback for sql errors in revision scripts. Yes, scripts should be tested first, and they are, but accidents happen. 

I used to think that if the 'Revision applied' message did not appear I could assume something went wrong. If it appeared then all is fine. However I am noticing that the message will appear when some statements in the revision folder fail.

Please consider providing the sql errors when revisions are applied. Apologies if I'm missing something.

**Comment by victorstanciu** [comment]
This should be fixed in https://github.com/victorstanciu/dbv/commit/cbbf24cad9204b2b49575b851d45efce0dfceefd. Can you confirm please?

**Comment by x56mike** [comment]
Thankyou victorstanciu for looking to this. This did not seem to fix the DELIMITER $$ problem.

Revision scripts which contain an update to a stored procedure and so contain the line "DELIMITER $$" will not execute past this line and will not report an error

Cheers,
x56mike

**Comment by x56mike** [comment]
Finally motivated enough to look into this. Solution is to remove DELIMITER $$ from revision script.

PHP does not need this line as it only executes one statement at a time (https://stackoverflow.com/questions/18409755/create-stored-procedures-with-pdo-in-php)

Potential problem that revision scripts will not work in a client like Workbench but I can live with that.
